# Generated by Django 6.0.3 on 2026-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('demo', 'Synthetic demo'), ('upload', 'Uploaded capture')], default='upload', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('packets', models.IntegerField(default=0)),
                ('duration_s', models.FloatField(default=0.0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('distinct_sources', models.IntegerField(default=0)),
                ('distinct_destinations', models.IntegerField(default=0)),
                ('findings', models.JSONField(default=list)),
                ('charts', models.JSONField(default=dict)),
                ('severity_counts', models.JSONField(default=dict)),
                ('report_rel', models.CharField(blank=True, default='', max_length=512)),
                ('json_rel', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
