"""Render an analysis run into a self-contained Markdown security report."""

from __future__ import annotations

import datetime as _dt
import math
import os

import pandas as pd

_SEV_BADGE = {"Critical": "🟥 Critical", "High": "🟧 High", "Medium": "🟨 Medium",
              "Low": "🟦 Low", "Info": "⬜ Info"}


def _fmt(v) -> str:
    if v is None or v is pd.NA:
        return ""
    if isinstance(v, float):
        if math.isnan(v):
            return ""
        return f"{v:.3f}".rstrip("0").rstrip(".") if v % 1 else f"{int(v)}"
    return str(v)


def df_to_md(df: pd.DataFrame, max_rows: int = 8) -> str:
    """Render a DataFrame as a GitHub-flavoured Markdown table (no deps)."""
    if df is None or df.empty:
        return "_(no rows)_"
    view = df.head(max_rows)
    cols = [str(c) for c in view.columns]
    head = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    body = []
    for row in view.itertuples(index=False, name=None):
        body.append("| " + " | ".join(_fmt(v) for v in row) + " |")
    extra = ""
    if len(df) > max_rows:
        extra = f"\n\n_… {len(df) - max_rows} more row(s) omitted._"
    return "\n".join([head, sep, *body]) + extra

def build_report(summary: dict, findings: list, charts: dict,
                 capture_name: str, outdir: str) -> str:
    """Assemble the full Markdown report body as a string."""
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: list[str] = []
    add = lines.append

    add(f"# PacketWatch Analysis Report\n")
    add(f"**Capture:** `{capture_name}`  ")
    add(f"**Generated:** {now}\n")

    # ---- Capture summary ------------------------------------------------
    add("## 1. Capture summary\n")
    add("| Metric | Value |")
    add("| --- | --- |")
    add(f"| Packets | {summary['packets']:,} |")
    add(f"| Duration | {summary['duration_s']:.1f} s |")
    add(f"| Total bytes | {summary['total_bytes']:,} |")
    add(f"| Avg. rate | {summary['avg_pps']:.1f} pkt/s |")
    add(f"| Distinct sources | {summary['distinct_sources']:,} |")
    add(f"| Distinct destinations | {summary['distinct_destinations']:,} |\n")

    for warning in summary.get("analysis_warnings", []):
        add(f"> **Capture limitation:** {warning}\n")

    # ---- Threat overview ------------------------------------------------
    add("## 2. Threat overview\n")
    if not findings:
        add("No threats detected by the current rule set. ✅\n")
    else:
        sev_counts: dict[str, int] = {}
        for f in findings:
            sev_counts[f.severity] = sev_counts.get(f.severity, 0) + 1
        parts = [f"{_SEV_BADGE.get(s, s)}: {n}"
                 for s, n in sorted(sev_counts.items(),
                                    key=lambda kv: -{'Critical':4,'High':3,'Medium':2,'Low':1,'Info':0}.get(kv[0],0))]
        add("**" + "  |  ".join(parts) + "**\n")
        add("| # | Severity | Category | Finding | MITRE ATT&CK |")
        add("| --- | --- | --- | --- | --- |")
        for i, f in enumerate(findings, 1):
            add(f"| {i} | {_SEV_BADGE.get(f.severity, f.severity)} | "
                f"{f.category} | {f.title} | {f.mitre} |")
        add("")

    # ---- Charts ---------------------------------------------------------
    if charts:
        add("## 3. Visual analytics\n")
        titles = {
            "findings": "Findings by severity",
            "protocols": "Protocol distribution",
            "timeline": "Traffic rate over time",
            "top_talkers": "Top talkers",
            "syn_scatter": "SYN targets over time",
            "dns_entropy": "DNS query length vs entropy",
        }
        for key, title in titles.items():
            if key in charts:
                rel = os.path.relpath(charts[key], outdir)
                add(f"**{title}**\n")
                add(f"![{title}]({rel})\n")

    # ---- Detailed findings ---------------------------------------------
    add("## 4. Detailed findings\n")
    if not findings:
        add("_Nothing to detail._\n")
    for i, f in enumerate(findings, 1):
        add(f"### 4.{i} {f.title}\n")
        add(f"- **Severity:** {_SEV_BADGE.get(f.severity, f.severity)}")
        add(f"- **Category:** {f.category}")
        add(f"- **MITRE ATT&CK:** {f.mitre}")
        if f.metrics:
            metric_str = ", ".join(f"`{k}={v}`" for k, v in f.metrics.items())
            add(f"- **Key metrics:** {metric_str}")
        add(f"\n{f.description}\n")
        add("**Evidence:**\n")
        add(df_to_md(f.evidence))
        add(f"\n**Recommended action:** {f.recommendation}\n")

    add("---")
    add("_Generated by PacketWatch. Detections are heuristic; validate "
        "findings against full packet context before acting._")
    return "\n".join(lines)


def write_report(summary: dict, findings: list, charts: dict,
                 capture_name: str, outdir: str,
                 filename: str = "report.md") -> str:
    """Build the report and write it to ``outdir/filename``; return the path."""
    os.makedirs(outdir, exist_ok=True)
    md = build_report(summary, findings, charts, capture_name, outdir)
    path = os.path.join(outdir, filename)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(md)
    return path
